export const mockStockEventsFractional = [
    {
      Action: "Market buy",
      Time: new Date("2023-01-01T10:00:00Z"),
      ISIN: "US0378331005",
      Ticker: "AAPL",
      Name: "Apple Inc.",
      NoOfShares: 0.3,
      PriceShare: 150.00,
      CurrencyPriceShare: "USD",
      ExchangeRate: "1",
      Result: "",
      CurrencyResult: "USD",
      Total: "1500.00",
      CurrencyTotal: "USD",
      WithholdingTax: "",
      CurrencyWithholdingTax: "",
      StampDutyReserveTax: "",
      CurrencyStampDutyReserveTax: "",
      TransactionFee: "0.50",
      FinraFee: "0.10",
      Notes: "before split",
      ID: "111111",
      CurrencyTransactionFee: "USD",
      CurrencyFinraFee: "USD"
    },
    {
      Action: "Market buy",
      Time: new Date("2023-02-01T10:00:00Z"),
      ISIN: "US0378331005",
      Ticker: "AAPL",
      Name: "Apple Inc.",
      NoOfShares: 1.5,
      PriceShare: 200.00,
      CurrencyPriceShare: "USD",
      ExchangeRate: "1",
      Result: "",
      CurrencyResult: "USD",
      Total: "1500.00",
      CurrencyTotal: "USD",
      WithholdingTax: "",
      CurrencyWithholdingTax: "",
      StampDutyReserveTax: "",
      CurrencyStampDutyReserveTax: "",
      TransactionFee: "0.50",
      FinraFee: "0.10",
      Notes: "before split",
      ID: "111112",
      CurrencyTransactionFee: "USD",
      CurrencyFinraFee: "USD"
    },
    {
      Action: "Split",
      Time: new Date("2023-04-01T00:00:00Z"),
      ISIN: "US0378331005",
      Ticker: "AAPL",
      Name: "Apple Inc.",
      NoOfShares: undefined,
      PriceShare: 30.00,
      CurrencyPriceShare: "USD",
      ExchangeRate: "1",
      Result: "",
      CurrencyResult: "USD",
      Total: "",
      CurrencyTotal: "USD",
      WithholdingTax: "",
      CurrencyWithholdingTax: "",
      StampDutyReserveTax: "",
      CurrencyStampDutyReserveTax: "",
      TransactionFee: "",
      FinraFee: "",
      Notes: "2x stock split",
      ID: "111113",
      CurrencyTransactionFee: "USD",
      CurrencyFinraFee: "USD",
      SplitFrom: 1,
      SplitTo: 2
    },
    {
      Action: "Market buy",
      Time: new Date("2023-05-01T14:30:00Z"),
      ISIN: "US0378331005",
      Ticker: "AAPL",
      Name: "Apple Inc.",
      NoOfShares: 0.3,
      PriceShare: 200.00,
      CurrencyPriceShare: "USD",
      ExchangeRate: "1",
      Result: "",
      CurrencyResult: "USD",
      Total: "1500.00",
      CurrencyTotal: "USD",
      WithholdingTax: "",
      CurrencyWithholdingTax: "",
      StampDutyReserveTax: "",
      CurrencyStampDutyReserveTax: "",
      TransactionFee: "0.50",
      FinraFee: "0.10",
      Notes: "bought after split",
      ID: "111114",
      CurrencyTransactionFee: "USD",
      CurrencyFinraFee: "USD"
    },
    {
      Action: "Market sell",
      Time: new Date("2023-06-01T14:30:00Z"),
      ISIN: "US0378331005",
      Ticker: "AAPL",
      Name: "Apple Inc.",
      NoOfShares: 1,
      PriceShare: 175.00,
      CurrencyPriceShare: "USD",
      ExchangeRate: "1",
      Result: "875.00",
      CurrencyResult: "USD",
      Total: "875.00",
      CurrencyTotal: "USD",
      WithholdingTax: "",
      CurrencyWithholdingTax: "",
      StampDutyReserveTax: "",
      CurrencyStampDutyReserveTax: "",
      TransactionFee: "0.50",
      FinraFee: "0.10",
      Notes: "sell after split",
      ID: "111115",
      CurrencyTransactionFee: "USD",
      CurrencyFinraFee: "USD"
    },
    {
      Action: "Limit sell",
      Time: new Date("2023-07-01T14:30:00Z"),
      ISIN: "US0378331005",
      Ticker: "AAPL",
      Name: "Apple Inc.",
      NoOfShares: 1,
      PriceShare: 185.00,
      CurrencyPriceShare: "USD",
      ExchangeRate: "1",
      Result: "875.00",
      CurrencyResult: "USD",
      Total: "875.00",
      CurrencyTotal: "USD",
      WithholdingTax: "",
      CurrencyWithholdingTax: "",
      StampDutyReserveTax: "",
      CurrencyStampDutyReserveTax: "",
      TransactionFee: "0.50",
      FinraFee: "0.10",
      Notes: "sold after split",
      ID: "111116",
      CurrencyTransactionFee: "USD",
      CurrencyFinraFee: "USD"
    }
  ]